const specialRulesAndPresenceCommonValues = [
  { label: "air", value: "air" },
  { label: "animal", value: "animal" },
  { label: "any", value: "any" },
  { label: "badlands", value: "badlands" },
  { label: "beasts", value: "beasts" },
  { label: "blight", value: "blight" },
  { label: "city", value: "city" },
  { label: "dahan", value: "dahan" },
  { label: "destroyed-presence", value: "destroyed-presence" },
  { label: "disease", value: "disease" },
  { label: "earth", value: "earth" },
  { label: "explorer", value: "explorer" },
  { label: "fast", value: "fast" },
  { label: "fear", value: "fear" },
  { label: "fire", value: "fire" },
  { label: "gain-range-1", value: "gain-range-1" },
  { label: "gain-range-2", value: "gain-range-2" },
  { label: "gain-range-3", value: "gain-range-3" },
  { label: "gain-range-x", value: "gain-range-x" },
  { label: "isolate", value: "isolate" },
  { label: "jungle", value: "jungle" },
  { label: "jungle-presence", value: "jungle-presence" },
  { label: "jungle-sand", value: "jungle-sand" },
  { label: "jungle-wetland", value: "jungle-wetland" },
  { label: "major", value: "major" },
  { label: "markerminus", value: "markerminus" },
  { label: "markerplus", value: "markerplus" },
  { label: "minor", value: "minor" },
  { label: "moon", value: "moon" },
  { label: "mountain", value: "mountain" },
  { label: "mountain-jungle", value: "mountain-jungle" },
  { label: "mountain-presence", value: "mountain-presence" },
  { label: "mountain-sand", value: "mountain-sand" },
  { label: "mountain-wetland", value: "mountain-wetland" },
  { label: "move-presence-1", value: "move-presence-1" },
  { label: "move-presence-2", value: "move-presence-2" },
  { label: "move-presence-3", value: "move-presence-3" },
  { label: "move-presence-4", value: "move-presence-4" },
  { label: "no-own-presence", value: "no-own-presence" },
  { label: "no-presence", value: "no-presence" },
  { label: "ocean", value: "ocean" },
  { label: "or", value: "or" },
  { label: "plant", value: "plant" },
  { label: "presence", value: "presence" },
  { label: "range", value: "range" },
  { label: "range-0", value: "range-0" },
  { label: "range-1", value: "range-1" },
  { label: "range-2", value: "range-2" },
  { label: "range-3", value: "range-3" },
  { label: "range-4", value: "range-4" },
  { label: "sacred-site", value: "sacred-site" },
  { label: "sand", value: "sand" },
  { label: "sand-presence", value: "sand-presence" },
  { label: "sand-wetland", value: "sand-wetland" },
  { label: "slow", value: "slow" },
  { label: "spirit", value: "spirit" },
  { label: "spirit", value: "spirit" },
  { label: "star", value: "star" },
  { label: "strife", value: "strife" },
  { label: "sun", value: "sun" },
  { label: "town", value: "town" },
  { label: "water", value: "water" },
  { label: "wetland", value: "wetland" },
  { label: "wetland-presence", value: "wetland-presence" },
  { label: "wilds", value: "wilds" },
];

const presenceValues = [
  ...specialRulesAndPresenceCommonValues,
  { label: "terror1", value: "terror1" },
  { label: "terror2", value: "terror2" },
  { label: "terror3", value: "terror3" },
];

export const presenceValuesSorted = presenceValues.sort((a, b) => {
  return a.label.localeCompare(b.label);
});

const specialRulesValues = [
  ...specialRulesAndPresenceCommonValues,
  { label: "custom1", value: "custom1" },
  { label: "custom2", value: "custom2" },
  { label: "custom3", value: "custom3" },
  { label: "custom4", value: "custom4" },
  {
    label: "jungle-mountain",
    value: "jungle-mountain",
  },
  { label: "range-[replace_w_icon]", value: "range-[replace_w_icon]" },
  { label: "sand-jungle", value: "sand-jungle" },
  { label: "sand-mountain", value: "sand-mountain" },
  { label: "terror-1", value: "terror-1" },
  { label: "terror-2", value: "terror-2" },
  { label: "terror-3", value: "terror-3" },
];

export const specialRulesValuesSorted = specialRulesValues.sort((a, b) => {
  return a.label.localeCompare(b.label);
});
