const iconValues = [
    { label: "air", value: "air" },
    { label: "animal", value: "animal" },
    { label: "any", value: "any" },
    { label: "badlands", value: "badlands" },
    { label: "beasts", value: "beasts" },
    { label: "blight", value: "blight" },
    { label: "city", value: "city" },
    { label: "custom1", value: "custom1" },
    { label: "custom2", value: "custom2" },
    { label: "custom3", value: "custom3" },
    { label: "custom4", value: "custom4" },
    { label: "dahan", value: "dahan" },
    { label: "destroyed-presence", value: "destroyed-presence" },
    { label: "disease", value: "disease" },
    { label: "earth", value: "earth" },
    { label: "explorer", value: "explorer" },
    { label: "fast", value: "fast" },
    { label: "fear", value: "fear" },
    { label: "fire", value: "fire" },
    { label: "gain-range-1", value: "gain-range-1" },
    { label: "gain-range-2", value: "gain-range-2" },
    { label: "gain-range-3", value: "gain-range-3" },
    { label: "gain-range-x", value: "gain-range-x" },
    { label: "isolate", value: "isolate" },
    { label: "jungle", value: "jungle" },
    { label: "jungle-mountain", value: "jungle-mountain" },
    { label: "jungle-presence", value: "jungle-presence" },
    { label: "jungle-sand", value: "jungle-sand" },
    { label: "jungle-wetland", value: "jungle-wetland" },
    { label: "major", value: "major" },
    { label: "markerminus", value: "markerminus" },
    { label: "markerplus", value: "markerplus" },
    { label: "minor", value: "minor" },
    { label: "moon", value: "moon" },
    { label: "mountain", value: "mountain" },
    { label: "mountain-jungle", value: "mountain-jungle" },
    { label: "mountain-presence", value: "mountain-presence" },
    { label: "mountain-sand", value: "mountain-sand" },
    { label: "mountain-wetland", value: "mountain-wetland" },
    { label: "move-presence-1", value: "move-presence-1" },
    { label: "move-presence-2", value: "move-presence-2" },
    { label: "move-presence-3", value: "move-presence-3" },
    { label: "move-presence-4", value: "move-presence-4" },
    { label: "no-own-presence", value: "no-own-presence" },
    { label: "no-presence", value: "no-presence" },
    { label: "ocean", value: "ocean" },
    { label: "or", value: "or" },
    { label: "plant", value: "plant" },
    { label: "presence", value: "presence" },
    { label: "range", value: "range" },
    { label: "range-[replace_w_icon]", value: "range-[replace_w_icon]" },
    { label: "range-0", value: "range-0" },
    { label: "range-1", value: "range-1" },
    { label: "range-2", value: "range-2" },
    { label: "range-3", value: "range-3" },
    { label: "range-4", value: "range-4" },
    { label: "sacred-site", value: "sacred-site" },
    { label: "sand", value: "sand" },
    { label: "sand-jungle", value: "sand-jungle" },
    { label: "sand-mountain", value: "sand-mountain" },
    { label: "sand-presence", value: "sand-presence" },
    { label: "sand-wetland", value: "sand-wetland" },
    { label: "slow", value: "slow" },
    { label: "spirit", value: "spirit" },
    { label: "spirit", value: "spirit" },
    { label: "star", value: "star" },
    { label: "strife", value: "strife" },
    { label: "sun", value: "sun" },
    { label: "terror-1", value: "terror-1" },
    { label: "terror-2", value: "terror-2" },
    { label: "terror-3", value: "terror-3" },
    { label: "town", value: "town" },
    { label: "water", value: "water" },
    { label: "wetland", value: "wetland" },
    { label: "wetland-presence", value: "wetland-presence" },
    { label: "wilds", value: "wilds" },
];

export const iconValuesSorted = iconValues.sort((a, b) => {
    return a.label.localeCompare(b.label);
});

const growthValues = [
    { label: "add-presence", value: "add-presence(" },
    { label: "add-token", value: "add-token(" },
    { label: "custom", value: "custom(" },
    { label: "damage", value: "damage(" },
    { label: "damage-1", value: "damage-1" },
    { label: "damage-2", value: "damage-2" },
    { label: "destroy-presence", value: "destroy-presence(" },
    { label: "discard", value: "discard(" },
    { label: "discard-card", value: "discard-card" },
    { label: "discard-cards", value: "discard-cards" },
    { label: "element-marker", value: "element-marker(" },
    { label: "energy-per-play", value: "energy-per-play" },
    { label: "fear", value: "fear(" },
    { label: "forget-power-card", value: "forget-power-card" },
    { label: "gain-card-play", value: "gain-card-play(" },
    { label: "gain-element", value: "gain-element(" },
    { label: "gain-energy", value: "gain-energy(" },
    { label: "gain-power-card", value: "gain-power-card" },
    { label: "gain-range", value: "gain-range(" },
    { label: "gather", value: "gather(" },
    { label: "ignore-range", value: "ignore-range" },
    { label: "incarna", value: "incarna(" },
    { label: "isolate", value: "isolate(" },
    { label: "make-fast", value: "make-fast(" },
    { label: "move-presence", value: "move-presence(" },
    { label: "or", value: "or(" },
    { label: "presence-node", value: "presence-node(" },
    { label: "push", value: "push(" },
    { label: "reclaim", value: "reclaim(" },
    { label: "replace", value: "replace(" },
];

export const growthValuesSorted = growthValues.sort((a, b) => {
    return a.label.localeCompare(b.label);
});